# Generated by Django 2.1.4 on 2020-11-05 20:23

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150)),
                ('href', models.CharField(max_length=255)),
                ('spotify_id', models.CharField(max_length=150)),
                ('type', models.CharField(max_length=100)),
                ('uri', models.CharField(max_length=255)),
                ('external_urls', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
